org: alli959
app: lesapp-data
service: lesapp-data
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  iam:
    role: arn:aws:iam::797132616636:role/Lesapp-Admin-Role

# package:
#   patterns:

# plugins:
# - serverless-s3-local
# - serverless-offline
# - serverless-plugin-common-excludes # this should go before serverless-plugin-include-dependencies
# - serverless-plugin-include-dependencies

functions:
  speak:
    handler: handler.speak
    events:
      - http:
          path: speak
          method: post
          cors: true
  get:
    handler: handler.get
    timeout: 15
    events:
      - http:
          path: get
          method: get
          cors: true
  auth:
    handler: auth.auth

  confirmSignUp:
    handler: auth.confirmSignUp

  save:
    handler: handler.save
    timeout: 15
    events:
      - http:
          path: save
          method: post
          cors: true
