useDotenv: true
org: alli959
app: lesapp-data
service: lesapp-data
profile: 
provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  profile: Lesapp-Admin-Role
  iam:
    role: arn:aws:iam::797132616636:role/Lesapp-Admin-Role
    

# package:
#   patterns:



functions:
  speak:
    handler: handler.speak
    events:
      - http:
          path: speak
          method: post
          cors: true
  get:
    handler: handler.get
    timeout: 15
    events:
      - http:
          path: get
          method: get
          cors: true
  auth:
    handler: auth.auth

  confirmSignUp:
    handler: auth.confirmSignUp

  save:
    handler: handler.save
    timeout: 15
    events:
      - http:
          path: save
          method: post
          cors: true

  listen:
    handler: handler.listen
    timeout: 15
    events:
      - http:
          path: listen
          method: post
          cors: true

  delete:
    handler: handler.delete
    timeout: 15
    events:
      - http:
          path: delete
          method: post
          cors: true


  generateImage:
    handler: handler.generateImage
    timeout: 30
    events:
      - http:
          path: generate-image
          method: post
          cors: true

  createtextkey:
    handler: handler.createtextkey
    timeout: 15
    events:
      - http:
          path: createtextkey
          method: post
          cors: true
